### ISSUE TITLE
still cannot compile on this release

### ISSUE THREAD

**Issue by hulinning2** [MemexAutomation/MTCACT#4]
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: MTCACT, Configuration: Debug Any CPU ------
1>CSC : error CS2001: Source file 'D:\Projects\Software\PCS 5053 MTConnect\MTCACT-master\MTCACT-1.0.0.2\MTCACT-1.0.0.2\MTCACT\MTCACT\Enumerators\Enum.PortValidationState.cs' could not be found.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Terry-Fedirko** [comment]
Not sure why this file (Enum.PortValidationState.cs) was not included in the pull but I verified that it is now part of the "master"

**Comment by Terry-Fedirko** [comment]
Hello Linh:

 

Please give it a try.    Not sure why this file is not committed but it is there now.

 

Regards, 

 

 


Terry Fedirko 


Senior .NET Developer 

 




Memex Automation

3425 Harvester Rd, Suite 105 

Burlington, Ontario 

L7N 3N1 Canada 

 


E-mail: 

Terry.Fedirko@memexoee.com 


Office: 

905-635-1540 ext 309

**Comment by hulinning2** [comment]
Working.  Thanks
